const React = require('react')

const Topic = require('../Topic')
const PortfolioList = require('../PortfolioList')

module.exports = () => (
    <Topic
        id="portfolio"
        title="Portfolio"
        description="Most of my work runs on closed environments, or under NDA (confidentiality agreement). So I can not show most of the projects I worked. But here, I'm showing some of the public projects."
    >
        <PortfolioList.Wrapper>
            <PortfolioList.Item
                title="Planedia"
                slug="planedia"
                thumb="/assets/images/port-planedia-thumb.jpg"
                image="/assets/images/port-planedia.jpg"
                description="Social trip planning platform, with third-party API integrations, such as OpenStreetMap, Facebook, Booking, and Kayak. I worked on this project for 3 years, initially as a backend (Writing REST API, migrating old/legacy data), and later as frontend (using React + Redux). I also was Tech Lead on this project."
                stack={[
                    'Javascript',
                    'React',
                    'Redux',
                    'SASS',
                    'PHP',
                    'Laravel',
                    'AWS',
                    'REST',
                    'Node.js',
                    'MongoDB',
                    'redis',
                    'Socket.IO',
                    'MySQL'
                ]}
            />
            <PortfolioList.Item
                title="Jimbo"
                slug="jimbo"
                thumb="/assets/images/port-jimbo-thumb.jpg"
                image="/assets/images/port-jimbo.jpg"
                description="Video-based Job Interview Platform. I worked on this project as a frontend, helped with tech decisions, I worked on DevOps tasks, Implemented Continous Delivery and wrote tests for the backend, using PHP Unit."
                stack={[
                    'Javascript',
                    'React',
                    'Redux',
                    'SASS',
                    'PHP',
                    'Laravel',
                    'PHP Unit',
                    'REST'
                ]}
            />
            <PortfolioList.Item
                title="Doutor Sucata"
                slug="dr-sucata"
                thumb="/assets/images/port-dr-sucata-thumb.jpg"
                image="/assets/images/port-dr-sucata.jpg"
                description="Mobile application created to sell used car parts from the junkyard. In this project, I created a mobile application for IOS/Android, using React Native."
                stack={['Javascript', 'React Native']}
            />
            <PortfolioList.Item
                title="241 App"
                slug="241"
                thumb="/assets/images/port-241-thumb.jpg"
                image="/assets/images/port-241.jpg"
                description="German coupon discount website. The interface was built with React, consuming a REST API. The website display discount coupons, offers and details from restaurants. The website also open inside a webview component from a IONIC application for smartphones."
                stack={['Javascript', 'React', 'SASS', 'REST']}
            />
            <PortfolioList.Item
                title="iCardapio"
                slug="icardapio"
                thumb="/assets/images/port-icardapio-thumb.jpg"
                image="/assets/images/port-icardapio.jpg"
                description="Food delivery website generator. On the image, a sample website generated by iCardapio Admin. The generated website allow the user check the restaurant menu, opening hours and some additional information. The user can create an account, make login, add menu items to the cart and make an order."
                stack={['Javascript', 'React', 'Emotion', 'Next.js', 'REST']}
            />
            <PortfolioList.Item
                title="Mundo das Especialidades"
                slug="mundo-das-especialidades"
                thumb="/assets/images/port-me-thumb.jpg"
                image="/assets/images/port-me.jpg"
                description="Static site generated by Gatsby. The CMS was built with PHP & Laravel, exposing a REST API for the static site generator grab the content during the build process. This site is served in 2 languages (Portuguese and Spanish), with a lot of articles and documents available for download."
                stack={[
                    'React',
                    'Emotion',
                    'Gatsby',
                    'PHP',
                    'Node.js',
                    'Laravel',
                    'REST'
                ]}
            />
            <PortfolioList.Item
                title="Rede Record"
                slug="record-tv"
                thumb="/assets/images/port-rede-record-thumb.jpg"
                image="/assets/images/port-rede-record.jpg"
                description="Brazilian television channel Rede Record website. This project was built with WordPress, and I worked creating the theme, some widgets and the plugin used for display videos from third-party partner."
                stack={[
                    'Javascript',
                    'jQuery',
                    'PHP',
                    'WordPress',
                    'CSS',
                    'HTML'
                ]}
            />
        </PortfolioList.Wrapper>
    </Topic>
)
